"""empty message

Revision ID: 00e2ac5cbaca
Revises: b092a22594a3
Create Date: 2020-09-27 17:28:37.711965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00e2ac5cbaca'
down_revision = 'b092a22594a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpool', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('carpool', sa.Column('time', sa.DateTime(), nullable=False))
    op.drop_column('carpool', 'hour')
    op.drop_column('carpool', 'when')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpool', sa.Column('when', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('carpool', sa.Column('hour', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('carpool', 'time')
    op.drop_column('carpool', 'date')
    # ### end Alembic commands ###
