"""empty message

Revision ID: 029ddb7154bb
Revises: 89563e4e7d56
Create Date: 2020-08-11 15:45:26.516127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '029ddb7154bb'
down_revision = '89563e4e7d56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_history', sa.Column('sum_of_rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_history', 'sum_of_rating')
    # ### end Alembic commands ###
