"""empty message

Revision ID: 0de4fc71e604
Revises: bc4d73e9ce71
Create Date: 2020-08-10 15:58:09.141548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0de4fc71e604'
down_revision = 'bc4d73e9ce71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_history',
    sa.Column('place_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('personal_rating', sa.Integer(), nullable=False),
    sa.Column('number_of_visits', sa.Integer(), nullable=False),
    sa.Column('personal_comments', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('place_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_history')
    # ### end Alembic commands ###
