"""empty message

Revision ID: 133b44f494f1
Revises: 0de4fc71e604
Create Date: 2020-08-11 15:24:40.030206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '133b44f494f1'
down_revision = '0de4fc71e604'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_history', sa.Column('number_of_times', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_history', 'number_of_times')
    # ### end Alembic commands ###
