"""empty message

Revision ID: 13e0b0c6dbc0
Revises: 24894c4c898b
Create Date: 2020-08-16 15:48:38.218617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13e0b0c6dbc0'
down_revision = '24894c4c898b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpool', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carpool', 'date')
    # ### end Alembic commands ###
