"""empty message

Revision ID: 15c64d467101
Revises: 1fe34b42e612
Create Date: 2020-08-09 15:30:45.874100

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '15c64d467101'
down_revision = '1fe34b42e612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_id', sa.String(length=100), nullable=True))
    op.drop_constraint('user_public_id_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['user_id'])
    op.drop_column('user', 'registered_on')
    op.drop_column('user', 'admin')
    op.drop_column('user', 'public_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('public_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('registered_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_public_id_key', 'user', ['public_id'])
    op.drop_column('user', 'user_id')
    # ### end Alembic commands ###
