"""empty message

Revision ID: 18c6546e1139
Revises: ad1c3dd706a1
Create Date: 2020-08-11 15:26:24.172470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18c6546e1139'
down_revision = 'ad1c3dd706a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_history', sa.Column('number_of_times', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_history', 'number_of_times')
    # ### end Alembic commands ###
