"""empty message

Revision ID: 24894c4c898b
Revises: 86f18baa1812
Create Date: 2020-08-16 15:43:42.948447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24894c4c898b'
down_revision = '86f18baa1812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpool', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carpool', 'date')
    # ### end Alembic commands ###
