"""empty message

Revision ID: 3c0700a219af
Revises: 486bb74c2055
Create Date: 2020-08-16 12:20:19.334234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c0700a219af'
down_revision = '486bb74c2055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gender', sa.Enum('Male', 'Female', 'Other', name='gender_types'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gender')
    # ### end Alembic commands ###
