"""empty message

Revision ID: 4827d6f224c7
Revises: ba0b50e76de6
Create Date: 2020-08-16 12:29:09.760218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4827d6f224c7'
down_revision = 'ba0b50e76de6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gender', sa.Enum('Male', 'Female', 'Other', name='gender'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gender')
    # ### end Alembic commands ###
