"""empty message

Revision ID: 5061275d08f6
Revises: 029ddb7154bb
Create Date: 2020-08-16 11:52:21.516876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5061275d08f6'
down_revision = '029ddb7154bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_history')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_table('user_history',
    sa.Column('place_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('personal_rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('number_of_visits', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('personal_comments', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sum_of_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='user_history_user_id_fkey'),
    sa.PrimaryKeyConstraint('place_id', name='user_history_pkey')
    )
    # ### end Alembic commands ###
