"""empty message

Revision ID: 594dbf8a8b2a
Revises: b469f1c7a665
Create Date: 2020-08-16 13:38:49.918123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '594dbf8a8b2a'
down_revision = 'b469f1c7a665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpool', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carpool', 'date')
    # ### end Alembic commands ###
