"""empty message

Revision ID: 5ef4e8d64fea
Revises: bbb29c89cac2
Create Date: 2020-08-10 14:53:35.400143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ef4e8d64fea'
down_revision = 'bbb29c89cac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_history', sa.Column('number_of_visits', sa.Integer(), nullable=False))
    op.add_column('user_history', sa.Column('personal_comments', sa.String(length=255), nullable=True))
    op.drop_column('user_history', 'rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_history', sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('user_history', 'personal_comments')
    op.drop_column('user_history', 'number_of_visits')
    # ### end Alembic commands ###
