"""empty message

Revision ID: 617d17c8d894
Revises: d7f581f9c6ea
Create Date: 2020-08-20 11:13:32.661537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '617d17c8d894'
down_revision = 'd7f581f9c6ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpool', sa.Column('driver_name', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'carpool', 'user', ['driver_name'], ['user_id'])
    op.drop_constraint('user_username_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_username_key', 'user', ['username'])
    op.drop_constraint(None, 'carpool', type_='foreignkey')
    op.drop_column('carpool', 'driver_name')
    # ### end Alembic commands ###
