"""empty message

Revision ID: 73473994420a
Revises: 5175c0fd4e4c
Create Date: 2020-08-20 14:57:26.333939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73473994420a'
down_revision = '5175c0fd4e4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpool', sa.Column('hour', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carpool', 'hour')
    # ### end Alembic commands ###
