"""empty message

Revision ID: 7bfd7d650830
Revises: 15c64d467101
Create Date: 2020-08-10 14:12:51.822709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bfd7d650830'
down_revision = '15c64d467101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_history',
    sa.Column('place_id', sa.String(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('personal_rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('place_id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('personal_rating'),
    sa.UniqueConstraint('rating')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_history')
    # ### end Alembic commands ###
