"""empty message

Revision ID: 82ffecdd793c
Revises: 617d17c8d894
Create Date: 2020-08-20 11:15:38.067944

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '82ffecdd793c'
down_revision = '617d17c8d894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpool', sa.Column('when', sa.String(length=255), nullable=False))
    op.drop_column('carpool', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpool', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('carpool', 'when')
    # ### end Alembic commands ###
