"""empty message

Revision ID: 89563e4e7d56
Revises: 355863b3ebef
Create Date: 2020-08-11 15:44:44.121362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89563e4e7d56'
down_revision = '355863b3ebef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_history', sa.Column('sum_of_rating', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_history', 'sum_of_rating')
    # ### end Alembic commands ###
