"""empty message

Revision ID: a89ca7217a78
Revises: d400d4213c1d
Create Date: 2020-08-16 16:13:21.181888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a89ca7217a78'
down_revision = 'd400d4213c1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('carpool_driver_name_fkey', 'carpool', type_='foreignkey')
    op.drop_column('carpool', 'driver_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpool', sa.Column('driver_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_foreign_key('carpool_driver_name_fkey', 'carpool', 'user', ['driver_name'], ['username'])
    # ### end Alembic commands ###
