"""empty message

Revision ID: b469f1c7a665
Revises: be0dddf4b8a7
Create Date: 2020-08-16 13:11:30.754181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b469f1c7a665'
down_revision = 'be0dddf4b8a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carpool',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('driver_name', sa.String(length=255), nullable=True),
    sa.Column('start', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=True),
    sa.Column('number_of_sits', sa.Integer(), nullable=True),
    sa.Column('animal', sa.Boolean(), nullable=True),
    sa.Column('road6', sa.Boolean(), nullable=True),
    sa.Column('comments', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['driver_name'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('destination'),
    sa.UniqueConstraint('start')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carpool')
    # ### end Alembic commands ###
