"""empty message

Revision ID: ba0b50e76de6
Revises: 3c0700a219af
Create Date: 2020-08-16 12:21:25.131478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba0b50e76de6'
down_revision = '3c0700a219af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gender', sa.Enum('Male', 'Female', 'Other', name='gender'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gender')
    # ### end Alembic commands ###
