"""empty message

Revision ID: be0dddf4b8a7
Revises: 4827d6f224c7
Create Date: 2020-08-16 12:33:02.107835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be0dddf4b8a7'
down_revision = '4827d6f224c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gender', sa.Enum('Male', 'Female', 'Other', name='gender'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gender')
    # ### end Alembic commands ###
