"""empty message

Revision ID: d400d4213c1d
Revises: 101b373e6306
Create Date: 2020-08-16 16:07:45.936993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd400d4213c1d'
down_revision = '101b373e6306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carpool', 'comments',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('carpool', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('carpool', 'destination',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('carpool', 'number_of_sits',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('carpool_date_key', 'carpool', type_='unique')
    op.drop_constraint('carpool_destination_key', 'carpool', type_='unique')
    op.drop_constraint('carpool_start_key', 'carpool', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('carpool_start_key', 'carpool', ['start'])
    op.create_unique_constraint('carpool_destination_key', 'carpool', ['destination'])
    op.create_unique_constraint('carpool_date_key', 'carpool', ['date'])
    op.alter_column('carpool', 'number_of_sits',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('carpool', 'destination',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('carpool', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('carpool', 'comments',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
