"""empty message

Revision ID: d7f581f9c6ea
Revises: a89ca7217a78
Create Date: 2020-08-20 11:11:58.396407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7f581f9c6ea'
down_revision = 'a89ca7217a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpool', sa.Column('driver_name', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'carpool', 'user', ['driver_name'], ['id'])
    op.drop_constraint('user_username_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_username_key', 'user', ['username'])
    op.drop_constraint(None, 'carpool', type_='foreignkey')
    op.drop_column('carpool', 'driver_name')
    # ### end Alembic commands ###
